-- Criar schemas para cada serviço
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS farms;
CREATE SCHEMA IF NOT EXISTS parcels;
CREATE SCHEMA IF NOT EXISTS crops;
CREATE SCHEMA IF NOT EXISTS livestock;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS reports;
CREATE SCHEMA IF NOT EXISTS admin;

-- Dar permissões necessárias
GRANT ALL PRIVILEGES ON SCHEMA users TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA farms TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA parcels TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA crops TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA livestock TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA inventory TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA finance TO postgres;
GRANT ALL PRIVILEICES ON SCHEMA reports TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA admin TO postgres;